name: Run Telegram Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # 02:00 UTC = 05:00 за Києвом (літній час, який почнеться за кілька днів)
    # 03:00 UTC = 05:00 за Києвом (зимовий час)
    # Поставимо з 02:00 до 10:00 UTC, щоб точно покрити ранок
    - cron: "*/15 2-10 * * *"

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py

      - name: Save memory
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f last_news.txt ]; then
            git add last_news.txt
            git commit -m "Оновлено дату відправки" || echo "Змін немає"
            git push
          fi
