name: Run Archive Collector

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  # schedule тимчасово вимкнено для архіву, щоб не було повторів

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
          # якщо у вас є requirements.txt, можна залишити pip install -r requirements.txt

      - name: Run Archive Script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python archive.py

      - name: Save memory
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f last_news.txt ]; then
            git add last_news.txt
            git commit -m "Оновлено дату після архіву" || echo "Змін немає"
            git push
          fi
